name: Wine-Staging-Source-Prepare

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Prepare Wine Staging Source
        run: |
          sudo apt update
          sudo apt install -y perl git wget xz-utils autoconf automake libtool
          chmod +x build_wine.sh
          export WINE_VERSION="10.15"
          export WINE_BRANCH="staging"
          export EXPERIMENTAL_WOW64="true"
          export DO_NOT_COMPILE="true"
          
          ./build_wine.sh
          
          # 打包源码
          cd $HOME/build_wine
          tar -czf wine-staging-src.tar.xz wine/
          mv wine-staging-src.tar.xz ../
          cd ..
          sha256sum *.tar.xz
          ls -la *.tar.xz
      - uses: actions/upload-artifact@v4
        with:
          name: Wine-Staging-Source
          path: ./*.tar.xz
