name: Wine-WoW64 SCR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: bootstraps.yml
          workflow_conclusion: success
          path: /opt
      - name: Prepare Wine Source Only
        run: |
          sudo apt update
          sudo apt install debootstrap perl git wget xz-utils bubblewrap autoconf
          sudo tar -C /opt -xpf /opt/Bootstraps/bootstraps.tar.xz
          chmod +x build_wine.sh
          export WINE_VERSION="latest"
          export EXPERIMENTAL_WOW64="false"  # 设置为 false，因为我们不编译
          export DO_NOT_COMPILE="true"       # 关键：设置为 true 只准备源码不编译
          
          WINE_BRANCH=staging ./build_wine.sh
          
          # 手动打包源码目录
          cd $HOME/build_wine
          tar -czf wine-staging-src.tar.gz wine/
          mv wine-staging-src.tar.gz ../
          cd ..
          sha256sum *.tar.gz
      - uses: actions/upload-artifact@v4
        with:
          name: Wine-Staging-Source
          path: ./*.tar.gz